name: cheminfo_WS1
channels:
  - rdkit
  - conda-forge
  - defaults
dependencies:
 - python=3.7
 - ipython
 - ipykernel
 - jupyter
 - notebook
 - ipywidgets
 - notebook
 - numpy
 - scipy
 - pandas
 - scikit-learn
 - matplotlib
 - seaborn
 - rdkit

